name: pub_mediator
version: 1.0.1
description: Diagnoses version conflicts between dependencies in Dart packages.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/pub_mediator
environment:
  sdk: ">=1.19.0 <=2.0.0"
dependencies:
  args: ^1.4.3
  dart2_constant: ^1.0.1+dart1
  cli_util: ^0.1.3
  console: '>=2.0.0 <=3.0.0'
  pub_semver: ^1.4.1
  pubspec: ^0.0.15

dev_dependencies:
  test: '>=0.12.0 <=1.0.0'

executables:
  mediator: main
